/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as VerifyPromptRouteImport } from './verify-prompt'
import { Route as VerifyFaceRouteImport } from './verify-face'
import { Route as VerifiedRouteImport } from './verified'
import { Route as ShowVibeRouteImport } from './show-vibe'
import { Route as OrderSummaryRouteImport } from './order-summary'
import { Route as GoTonightRouteImport } from './go-tonight'
import { Route as FeedRouteImport } from './feed'
import { Route as EventsRouteImport } from './events'
import { Route as BuyDrinksRouteImport } from './buy-drinks'
import { Route as IndexRouteImport } from './index'

const VerifyPromptRoute = VerifyPromptRouteImport.update({
  id: '/verify-prompt',
  path: '/verify-prompt',
  getParentRoute: () => rootRouteImport,
} as any)

const VerifyFaceRoute = VerifyFaceRouteImport.update({
  id: '/verify-face',
  path: '/verify-face',
  getParentRoute: () => rootRouteImport,
} as any)

const VerifiedRoute = VerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => rootRouteImport,
} as any)

const ShowVibeRoute = ShowVibeRouteImport.update({
  id: '/show-vibe',
  path: '/show-vibe',
  getParentRoute: () => rootRouteImport,
} as any)

const OrderSummaryRoute = OrderSummaryRouteImport.update({
  id: '/order-summary',
  path: '/order-summary',
  getParentRoute: () => rootRouteImport,
} as any)

const GoTonightRoute = GoTonightRouteImport.update({
  id: '/go-tonight',
  path: '/go-tonight',
  getParentRoute: () => rootRouteImport,
} as any)

const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)

const BuyDrinksRoute = BuyDrinksRouteImport.update({
  id: '/buy-drinks',
  path: '/buy-drinks',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy-drinks': typeof BuyDrinksRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/go-tonight': typeof GoTonightRoute
  '/order-summary': typeof OrderSummaryRoute
  '/show-vibe': typeof ShowVibeRoute
  '/verified': typeof VerifiedRoute
  '/verify-face': typeof VerifyFaceRoute
  '/verify-prompt': typeof VerifyPromptRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy-drinks': typeof BuyDrinksRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/go-tonight': typeof GoTonightRoute
  '/order-summary': typeof OrderSummaryRoute
  '/show-vibe': typeof ShowVibeRoute
  '/verified': typeof VerifiedRoute
  '/verify-face': typeof VerifyFaceRoute
  '/verify-prompt': typeof VerifyPromptRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy-drinks': typeof BuyDrinksRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/go-tonight': typeof GoTonightRoute
  '/order-summary': typeof OrderSummaryRoute
  '/show-vibe': typeof ShowVibeRoute
  '/verified': typeof VerifiedRoute
  '/verify-face': typeof VerifyFaceRoute
  '/verify-prompt': typeof VerifyPromptRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy-drinks'
    | '/events'
    | '/feed'
    | '/go-tonight'
    | '/order-summary'
    | '/show-vibe'
    | '/verified'
    | '/verify-face'
    | '/verify-prompt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy-drinks'
    | '/events'
    | '/feed'
    | '/go-tonight'
    | '/order-summary'
    | '/show-vibe'
    | '/verified'
    | '/verify-face'
    | '/verify-prompt'
  id:
    | '__root__'
    | '/'
    | '/buy-drinks'
    | '/events'
    | '/feed'
    | '/go-tonight'
    | '/order-summary'
    | '/show-vibe'
    | '/verified'
    | '/verify-face'
    | '/verify-prompt'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyDrinksRoute: typeof BuyDrinksRoute
  EventsRoute: typeof EventsRoute
  FeedRoute: typeof FeedRoute
  GoTonightRoute: typeof GoTonightRoute
  OrderSummaryRoute: typeof OrderSummaryRoute
  ShowVibeRoute: typeof ShowVibeRoute
  VerifiedRoute: typeof VerifiedRoute
  VerifyFaceRoute: typeof VerifyFaceRoute
  VerifyPromptRoute: typeof VerifyPromptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-prompt': {
      id: '/verify-prompt'
      path: '/verify-prompt'
      fullPath: '/verify-prompt'
      preLoaderRoute: typeof VerifyPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-face': {
      id: '/verify-face'
      path: '/verify-face'
      fullPath: '/verify-face'
      preLoaderRoute: typeof VerifyFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified': {
      id: '/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show-vibe': {
      id: '/show-vibe'
      path: '/show-vibe'
      fullPath: '/show-vibe'
      preLoaderRoute: typeof ShowVibeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-summary': {
      id: '/order-summary'
      path: '/order-summary'
      fullPath: '/order-summary'
      preLoaderRoute: typeof OrderSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-tonight': {
      id: '/go-tonight'
      path: '/go-tonight'
      fullPath: '/go-tonight'
      preLoaderRoute: typeof GoTonightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-drinks': {
      id: '/buy-drinks'
      path: '/buy-drinks'
      fullPath: '/buy-drinks'
      preLoaderRoute: typeof BuyDrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyDrinksRoute: BuyDrinksRoute,
  EventsRoute: EventsRoute,
  FeedRoute: FeedRoute,
  GoTonightRoute: GoTonightRoute,
  OrderSummaryRoute: OrderSummaryRoute,
  ShowVibeRoute: ShowVibeRoute,
  VerifiedRoute: VerifiedRoute,
  VerifyFaceRoute: VerifyFaceRoute,
  VerifyPromptRoute: VerifyPromptRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
